seed: 1234
device: null

dataset:
  train:
    type: "case_folders"
    case_root: "D:/nnunet/2D_test_v2"
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    image_size: [256, 256]
    normalize: "range_m11"

model:
  image_size: 256
  inner_channel: 32
  channel_mults: [1, 2, 4]
  attn_res: []
  res_blocks: 1
  dropout: 0.1

diffusion:
  sample_steps: 100
  beta_schedule:
    schedule: "linear"
    n_timestep: 100
    linear_start: 0.0001
    linear_end: 0.02

train:
  epochs: 20
  batch_size: 16
  num_workers: 0
  lr: 0.0001
  weight_decay: 0.0

logging:
  use_swanlab: true
  project: "palette_decoupling_cbct"
  experiment_name: "bone_1175cases_fulltrain_std_aug"

output:
  root: "D:/vscode_workplace/codeplace/palette/outputs/bone_1175cases_fulltrain_std_aug"
