seed: 1234
device: null

dataset:
  train:
    type: "case_folders"
    case_root: "D:/nnunet/2D"
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    image_size: [256, 256]
    normalize: "range_m11"
  val:
    type: "case_folders"
    case_root: "D:/nnunet/2D"
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    image_size: [256, 256]
    normalize: "range_m11"
  test:
    type: "case_folders"
    case_root: "D:/nnunet/2D"
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    image_size: [256, 256]
    normalize: "range_m11"

model:
  image_size: 256
  inner_channel: 32
  channel_mults: [1, 2, 4,8]
  num_head_channels: 32
  attn_res: [16]
  res_blocks: 2

  dropout: 0.1

diffusion:
  sample_steps: 1000
  beta_schedule:
    schedule: "linear"
    n_timestep: 2000
    linear_start: 0.0001
    linear_end: 0.02

train:
  epochs: 20
  batch_size: 16
  val_batch_size: 1
  num_workers: 0
  lr: 0.0001
  weight_decay: 0.0
  val_every: 1
  val_sample_steps: 20

logging:
  use_swanlab: true
  project: "palette_decoupling_cbct"
  experiment_name: "bone_10cases_std_aug_full_to_lr"

output:
  root: "D:/vscode_workplace/codeplace/palette/outputs/bone_cases_std_aug"
