seed: 1234
device: null

dataset:
  train:
    type: "case_folders"
    case_root: "D:/nnunet/2D_test_v2"
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    image_size: [256, 256]
    normalize: "range_m11"

model:
  image_size: 256
  inner_channel: 64
  channel_mults: [1, 2, 4, 8]
  attn_res: [16]
  res_blocks: 2
  dropout: 0.2

diffusion:
  sample_steps: 1000
  beta_schedule:
    schedule: "linear"
    n_timestep: 2000
    linear_start: 0.000001
    linear_end: 0.01

train:
  epochs: 20
  batch_size: 4
  num_workers: 0
  lr: 0.00005

logging:
  use_swanlab: true
  project: "palette_decoupling_cbct"
  experiment_name: "bone_1175cases_palette_originalish"

output:
  root: "D:/vscode_workplace/codeplace/palette/outputs/bone_1175cases_palette_originalish"
