seed: 1234
device: null

dataset:
  train:
    type: "case_folders"
    #case_root: "/public_bme2/bme-cuizhm/maxquan/Datasets/CBCT/2D"
    case_root: "D:/nnunet/2D"
    split: "train"
    split_seed: 1234
    train_ratio: 0.9
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    target_mode: "dual"
    image_size: [256, 256]
    normalize: "fixed_range_m11"
    value_range: [0.0, 6.0]
    clip_range: [0.0, 6.0]
  val:
    type: "case_folders"
    #case_root: "/public_bme2/bme-cuizhm/maxquan/Datasets/CBCT/2D"
    case_root: "D:/nnunet/2D"
    split: "val"
    split_seed: 1234
    train_ratio: 0.9
    variants: ["std", "aug"]
    condition_template: "{variant}_full.npy"
    target_templates:
      - "{variant}_left.npy"
      - "{variant}_right.npy"
    target_mode: "dual"
    image_size: [256, 256]
    normalize: "fixed_range_m11"
    value_range: [0.0, 6.0]
    clip_range: [0.0, 6.0]

model:
  image_size: 256
  inner_channel: 64
  channel_mults: [1, 2, 4,8]
  attn_res: [16]
  res_blocks: 2
  dropout: 0.2
  branch_decoder:
    enabled: true
    shared_blocks: 8

diffusion:
  beta_schedule:
    schedule: "linear"
    n_timestep: 1000
    linear_start: 0.0001
    linear_end: 0.02
  branch_loss_weights:
    left: 1.0
    right: 1.0
  consistency_loss:
    enabled: false

train:
  max_steps: 450000
  batch_size: 16
  val_batch_size: 16
  num_workers: 0
  lr: 0.00008
  lr_schedule:
    enabled: true
    type: "cosine_with_warmup"
    warmup_steps: 10000
    warmup_start_lr: 0.0
    min_lr: 0.00002

  weight_decay: 0.0
  resume_checkpoint: null
  ema_decay: 0.9999
  ema_start_step: 100
  validate_every_steps: 1000
  save_every_steps: 10000
  log_every_steps: 50
  best_metric: "val_mae"

validation:
  max_batches: 32
  fid_every_steps: 0
  sampler:
    sampler: "ddim"
    steps: 50
    eta: 0.0

logging:
  use_swanlab: true
  use_tensorboard: true
  project: "palette_decoupling_cbct"
  experiment_name: "cbct_1175_full_to_lr_branch_baseline"
  mode: null
  logdir: null
  tensorboard_logdir: null
  run_id: null
  resume: null

output:
  #root: "/public_bme2/bme-cuizhm/maxquan/Projects/Replicate/Genai/palette/condition_injection/CBCT_decouping_diffusion/output/branch"
  root : "D:/vscode_workplace/codeplace/palette/outputs/branch_baseline"
